FROM golang:1.21 AS builder

ARG ARCH=arm64

WORKDIR /tasmota-exporter/
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=$ARCH go build -o app ./cmd

FROM arm64v8/alpine:latest
WORKDIR /root/

COPY --from=builder /tasmota-exporter/app app

CMD ["./app"]
