{
 "title": "Tasmota",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "device",
    "query": {
     "query": "label_values(tasmota_status_sts_wifi_rssi, status_device_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasmota_status_sts_uptime_sec{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tasmota_status_sts_load_avg{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  { "title": "Switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "State",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "tasmota_status_power{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  { "title": "WiFi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "tasmota_status_sts_wifi_signal{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "tasmota_status_sts_wifi_rssi{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "tasmota_status_sns_energy_current{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "tasmota_status_sns_energy_power{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "tasmota_status_sns_energy_voltage{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  {
   "title": "Reactive Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "targets": [
    {
     "expr": "tasmota_status_sns_energy_reactive_power{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  {
   "title": "Apparent Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "tasmota_status_sns_energy_apparent_power{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tasmota_status_sns_energy_factor{status_device_name=~\"$device\"}",
     "legendFormat": "{{status_device_name}}"
    }
   ]
  }
 ]
}